### ISSUE TITLE
When I run your model, there will be this error, is there any solution? Thank you very much!

### ISSUE THREAD

**Issue by 77Chen** [amirhfarzaneh/lsoftmax-pytorch#4]
When I run your model, there will be this error, is there any solution? Thank you very much!

one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 10]], which is output 0 of MmBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by longlongvip** [comment]
I meet the same question, but I don't know solve it.

**Comment by 77Chen** [comment]
> I meet the same question, but I don't know solve it.

I queried that this problem was caused by the inplace operation after the pytorch revision， I solved the problem by installing pytorch0.4.1

**Comment by longlongvip** [comment]
Yes,it works,thanks haha
