### ISSUE TITLE
why not use torch.acos

### ISSUE THREAD

**Issue by jasstionzyf** [amirhfarzaneh/lsoftmax-pytorch#5]
hi, very thanks for your contributions.
when i read calculate_cos_m_theta function in LSoftmaxLinear implementions,
i notice that torch.cos(2*torch.acos(cos_theta)) can simply compute cos_m_theta , why not use it ?
maybe i have some misunderstands

**Comment by amirhfarzaneh** [comment]
As I mentioned in the readme acos causes numerical error

**Comment by jasstionzyf** [comment]
https://github.com/pytorch/pytorch/issues/8069     
there is a way to fix the issues
